### ISSUE TITLE
IFI > Esquema de URIs de provincias/NUTS3

### ISSUE THREAD

**Issue by dportoles** [Cross-Forest/Ontologies#1]
Tenemos el código NUTS3 (ES421), el id de inventario (3/4 para España, 6 para PT).

Opciones:
http://crossforest.eu/ifi/data/nuts3/ES/ES424
http://crossforest.eu/ifi/data/nuts3/ES424
(...)

¿Debemos considerar el id de inventario?
A priori, parece que no porque es algo bastante estable en el tiempo, pero podría haber cambios en las provincias en función de la versión de inventario....  (los inventarios se remontan a mucho tiempo atrás)

**Comment by dportoles** [comment]
Existe también la iniciativa geovocab
e.g. http://nuts.geovocab.org/id/ES425

El principal problema es que las portuguesas no encajan en código y denominación.
Las españolas sí en código, pero no en denominación.
Adjunto excel con la comparativa: 
[comparativaIFI_Geovocab_NUTS3.xlsx](https://github.com/Cross-Forest/Ontologies/files/6075920/comparativaIFI_Geovocab_NUTS3.xlsx)

Podría incluirse que las españolas son concepto equivalente, pero no las portuguesas

**Comment by dportoles** [comment]
En IFN se habla de provincia e incluso se incluyen en la propia ontología como individuos.
e.g. http://crossforest.eu/ifn/data/province/01

Aquí es diferente ya que se cita NUTS3 (son similares) pero es un concepto más extendido en Europa. Respeto la denominación NUTS3.

Se verá de incluir relaciones a las URI de IFN pero no se reusarán por este motivo. Además, los códigos son diferentes (en IFN es de 01 a 52, en el IFI es p.ej. 111, 421...)

Finalmente se propone, por ahora, utilizar las URI sin id de inventario. Se entiende es suficientemente estable en el tiempo y si hubiera una reorganización administrativa, confiemos en que le pongan otros códigos o haya forma de diferenciarlos.

**Comment by guiveg** [comment]
De acuerdo con no incluir el id de inventario en las IRIs de las provincias.

Bien con el estudio de NUTS3 y Geovocab. Podemos alinearlos posteriormente a partir de esto.

**Comment by dportoles** [comment]
Hay un detalle importante al respecto.
Al final se van a generar también las URI de NUTS1 y NUTS2, así como sus relaciones jerárquicas.

Las NUTS2 hacen falta ya que hay valores de IFN4 en IFI que se tienen desglosados por NUTS2 y no por NUTS3.
