### ISSUE TITLE
Errata en ontología COS

### ISSUE THREAD

**Issue by dportoles** [Cross-Forest/Ontologies#2]
Hay una errata aquí, en vez de Us9200 deberia ser Use9200

https://github.com/Cross-Forest/Ontologies/blob/49f81773a381cdd920431ff01afe8440a8ff6f84/cos/cos-core.ttl#L454

@jm-gimenez-garcia Como no sé cómo se genera esta parte, no sé si basta con cambiarlo o si hay que cambiar algún script que genera esto como resultado.
Si solo es cambiarlo, lo puedo cambiar directamente yo.

**Comment by guiveg** [comment]
Creo que puedes cambiarlo directamente, David
